redhat-documentation/supplementary-style-guide

LICENSE.txt, README.md
This PR adds the license file to the repository and updates the README to now include license information.
=> Add license and update readme with license info

.gitignore
.gitignore file with master.html only
=> .gitignore file with master

supplementary_style_guide/introduction/about-guide.adoc
Added admonition `Important: This document is a work in progress.`
=> Added "Work in progress" note

supplementary_style_guide/style_guidelines/code-commands.adoc, supplementary_style_guide/style_guidelines/general-formatting.adoc, supplementary_style_guide/style_guidelines/grammar.adoc, supplementary_style_guide/style_guidelines/graphical-interfaces.adoc, supplementary_style_guide/style_guidelines/links.adoc, supplementary_style_guide/style_guidelines/specific-doc-types.adoc
This PR adds anchors to each file in the `style_guidelines` directory.
=> Add anchors to style files

.travis.yml, supplementary_style_guide/master.adoc
I added .travis.yml, which enables publishing the Asciidoc source to HTML output.
=> add_travis_config Added .travis.yml to enable publishing HTML output

supplementary_style_guide/introduction/about-guide.adoc, supplementary_style_guide/master.adoc, supplementary_style_guide/style_guidelines/graphical-interfaces.adoc
Preview (internal): http://file.rdu.redhat.com/~ahoffer/2020/pr-11/master.html#graphical-interfaces
=> Adding a style guideline entry

GUIDELINES.adoc
@redhat-documentation/ccs-style-council Style entry guidance, please review! Let me know if you can think of any considerations that we need to add here.
See https://github.com/redhat-documentation/supplementary-style-guide/blob/master/supplementary_style_guide/style_guidelines/graphical-interfaces.adoc for an example implementation.
=> Adding guidelines for style entries

supplementary_style_guide/style_guidelines/graphical-interfaces.adoc
=> Fixing UI terms

supplementary_style_guide/introduction/about-guide.adoc
Per #14
Preview: http://file.rdu.redhat.com/~ahoffer/2020/style_guide/pr-20/master.html#_about_this_guide
=> Reference this guide first, and notify of deviations

README.md
@redhat-documentation/ccs-style-council For review please.
=> Adding a link to the guide

supplementary_style_guide/style_guidelines/general-formatting.adoc
Hi @bergerhoffer,
Here's my attempt at doc-ing the exception for date formats.
Please lemme know watcha think.
Thanks,
--Greg
=> First draft at documenting date format exceptions.

supplementary_style_guide/style_guidelines/general-formatting.adoc
Added information about Admonitions.
=> Added information about Admonitions

supplementary_style_guide/style_guidelines/graphical-interfaces.adoc
Per today's meeting, removing this menu item entry.
=> Removing menu item entry

supplementary_style_guide/style_guidelines/general-formatting.adoc
Preview (internal): http://file.rdu.redhat.com/~ahoffer/style_guide/replaceable-values/master.html#user-replaced-values
=> Adding guidance for replaceable values

supplementary_style_guide/style_guidelines/code-commands.adoc
Entry for review @redhat-documentation/ccs-style-council
=> Add long code examples in procedures

supplementary_style_guide/style_guidelines/code-commands.adoc
Code format style entry for review: @redhat-documentation/ccs-style-council
=> Code format

supplementary_style_guide/style_guidelines/links.adoc
Addresses *issue 29 Add guideline for links to Red Hat Knowledgebase articles*
=> issue29 Links to RH KB articles.

supplementary_style_guide/style_guidelines/code-commands.adoc, supplementary_style_guide/style_guidelines/general-formatting.adoc, supplementary_style_guide/style_guidelines/links.adoc
Performed a first pass edit; passing off to Joan Hoyt for final proofing
=> edited supplementary style guide entries

supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
Added "an" before adjective in two places
=> revised f.adoc to add an before adjective in two places

supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc, supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc, supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-satellite6.adoc
Been seeing varied usage coming in to OpenShift docs, so thought might as well get some guidance down somewhere (didn't find in IBM SG).
Other usage examples in the wild for consideration, FWIW:
* [Git docs](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository)
* [GitHub docs](https://docs.github.com/en/github/getting-started-with-github/set-up-git)
* [Wiki entry](https://en.wikipedia.org/wiki/Git)
=> Add glossary entry for Git

ADMIN.adoc, README.md
@stoobie @cbudz @bergerhoffer @redhat-documentation/ccs-style-council Please feel free to review the administrator responsibilities and let me know if you'd like me add or change anything. Thank you.
=> Add a checklist of administrator responsibilities

HISTORY.md
Just adding April updates to the history page
=> Updating update history for April 2021

supplementary_style_guide/style_guidelines/general-formatting.adoc
@bergerhoffer @cbudz @redhat-documentation/ccs-style-council 
I have added initial content for the guidelines on using product name and version attributes.
The additions that I made so far are very general and should be applicable to all project.
However I do feel that more details are necessary and I would like to know you input on the current content before I proceed with adding more of it.
Note, that this is still a work in progress and you can find some of my proposed content in the comments. this content is not complete and will have to be further developed.
Please let me know your thoughts and comments. Thank you.
=> Add guidelines about using attributes for product names and versions

supplementary_style_guide/style_guidelines/general-formatting.adoc
Added guidance about using an unnumbered bullet for single step procedures.
=> Added info about single step procedures

supplementary_style_guide/style_guidelines/specific-doc-types.adoc
Hi folks,
Here is the suggested entry for how to write release note doc texts. It's quite a lengthy entry so needs feedback. The content is taken from this mojo article:
https://mojo.redhat.com/docs/DOC-1216602?sr=inbox&ru=50169
It includes a type of variable, so their format should follow the guidance that the Supplementary Style Guide eventually settles on.
=> Added release note doc text guidance

supplementary_style_guide/style_guidelines/general-formatting.adoc
Add a section to the General Formatting section for conversational style guidance.
=> added entry for Conversational style

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
PR for issue #76 . @bergerhoffer @cbudz Ready for your review and approval.
=> Add entry for standalone

supplementary_style_guide/introduction/about-guide.adoc
This PR adds a header to the introduction to better and more easily  inform readers of the order of operations on using the supplement.
=> Add how to use header

supplementary_style_guide/style_guidelines/general-formatting.adoc
Preview: http://file.rdu.redhat.com/~ahoffer/style_guide/contractions/master.html#contractions
Addresses #79.
=> Added guidance on avoiding contractions

.travis.yml, supplementary_style_guide/master.adoc
Copy files to fix icons not appearing
=> [WIP] Adding step to copy images

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/q.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
Fixes: Added icons to P,Q,R of supplementary style guide glossary.
Signed-off-by: ktothill@redhat.com
=> UPDATE_SSG Added icons to P,Q,R of supplementary style guide

supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
Added icons to letters l, m, n, and o in General conventions.
=> added icons for m-o

HISTORY.md, README.md
Added new items for the last month and added links.
=> Updating history for July 2021

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc
https://github.com/redhat-documentation/supplementary-style-guide/issues/83
=> Add "as expected" to a.adoc

HISTORY.md, supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc, supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc
Addresses #108.
Removing "host name" entry and updating all instances of "host name" in the guide to "hostname".
Also updated the history file with the council's decision.
=> Removed 'host name' entry and updated all instances to hostname

supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift-container-storage.adoc
@bergerhoffer please feel free to merge this when you have a chance. Thank you.
=> fix "on-premises" -> "on-premise" in Openshift Container Storage

supplementary_style_guide/style_guidelines/general-formatting.adoc
Addresses issue #88
Hi folks, 
Here is a fist attempt to include guidance to replace whitelist and blacklist in documentation.
I could use some help deciding if the examples are helpful and if not and generally how to format this guidance.
Thanks!
-Naomi
=> Adding guidance for conscious language replacements

supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc, supplementary_style_guide/style_guidelines/general-formatting.adoc
Adding quick start entry for OpenShift, as per https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/term_glossary.adoc#quick-start
=> Adding quick start entry for OpenShift

supplementary_style_guide/style_guidelines/specific-doc-types.adoc
=> issue81 Updating boiler-plate text for technology preview.

supplementary_style_guide/introduction/about-guide.adoc
Added note to the About section to clarify which guide is the source of truth for what type of information. Based on [Issue#74](https://github.com/redhat-documentation/supplementary-style-guide/issues/74).
=> added note about sources of truth

supplementary_style_guide/style_guidelines/code-commands.adoc
Draft content to address the following issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/121
=> Document CLI commands that require elevated privileges

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc, supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-data-grid.adoc, supplementary_style_guide/master.adoc
add data grid terms to the glossary
https://issues.redhat.com/browse/JDG-4940
=> RHDG terminology

supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-directory-server.adoc, supplementary_style_guide/master.adoc
Add RHDS terminology from this doc: https://docs.google.com/document/d/1uyD9i8Vbfa75KbGDPrGdxYIa8UFlH4PNPbD7Eltp4Gk/edit
=> RHDS terminology

supplementary_style_guide/master.adoc, supplementary_style_guide/style_guidelines/managed-services.adoc, supplementary_style_guide/style_guidelines/mananged-services.adoc
Adding new section for guidelines on writing for managed services.
=> Add managed services section

supplementary_style_guide/style_guidelines/general-formatting.adoc
This PR  adds the terms master/slave under the **Conscious Language** title and suggests alternatives as per the linked Conscious Language GitHub repo.
=> Add master/slave to the Conscious Language section

supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-enterprise-linux.adoc
All newly added terms are sorted alphabetically below the already published content starting on line 71 with heading *NEWLY ADDED*
Please check if the descriptions are ok for the SSG, some terms include links to the RHEL docs -> please decide if it is ok or if they should be removed.
There are two duplicate terms: ansible-playbook and ansible-playbook-sysroles
=> Rhel product conventions new terms

HISTORY.md
=> Updating history as of April 25

supplementary_style_guide/style_guidelines/general-formatting.adoc
Test to ensure GitHub token is working.
=> updated Contractions

supplementary_style_guide/style_guidelines/general-formatting.adoc
Reverts redhat-documentation/supplementary-style-guide#183
=> Revert "updated Contractions"

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
This PR adds definitions to the glossary of "privilege" and "permissions.
=> 151 - Add definitions of privileges and permissions

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
Addresses #198.
Preview: http://file.rdu.redhat.com/~ahoffer/style_guide/customer/master.html#customer
=> Adding customer to the glossary

GUIDELINES.adoc
Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/173
=> Add entry for italic and double quotes use

supplementary_style_guide/style_guidelines/general-formatting.adoc
This PR adds information about references product costs.
=> Added Cost Reference Section

supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
For details, see https://en.wikipedia.org/wiki/.NET
=> Updated ".NET Core" entry, added ".NET" entry

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
The scope of this PR is to propose terms that are specific to OCP.
Replaces #222
=> adds terms to the glossary

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc, supplementary_style_guide/style_guidelines/grammar.adoc
https://issues.redhat.com/browse/RHELPLAN-103677
=> Added networking terms to glossary

supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc, supplementary_style_guide/main.adoc, supplementary_style_guide/style_guidelines/support.adoc
This pull request resolves Issue 216.
https://github.com/redhat-documentation/supplementary-style-guide/issues/216
Added a new section called Support that can expand over time
Added an entry for Technology Previews based on CCS guidelines
Added an entry in General Conventions
=> added a section called Support, with the first entry Technology Preview

supplementary_style_guide/style_guidelines/grammar.adoc
This PR adds a style entry with guidance for using homographs.
=> Issue 220 - add style guidance for homographs

supplementary_style_guide/style_guidelines/links.adoc
PR that rebased #28 and will continue addressing feedback from that PR in future updates here.
Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-links.html#links
=> Added link guidance content

HISTORY.md
=> Updating history through October 2022

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
Updated entries for BIOS, firmware, and PXE (which refers to BIOS/firmware)
=> 249 Updated terms related to BIOS and firmware

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
Fixing caution icon from #250 
Original issue #249 
Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-bios.html#bios
=> Updating caution icon

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/173
Related Jira(s):
- https://github.com/redhat-documentation/supplementary-style-guide/pull/215
=> italics-quotes-a-to-f: Apply correct use of italics and quotes to a-z glossary

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
=> Added new entries for plugin and plug-in

supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
Adds regular expression and regex to SSG Glossary. See https://github.com/redhat-documentation/supplementary-style-guide/issues/226
=> Add regular expression to SSG glossary

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/x.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/y.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/z.adoc
Updated letter files S-Z for consistent usage of quotes and italics.
Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-italics.html
Issue #173
=> Updating for italics and quotes consistency, S-Z

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
=> Issue191 fuse updates

HISTORY.md
Updating history as of November 2022
=> Updating history as of Nov 2022

supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
=> GitHub-254: Removing numbers entry in favor of following ISG

supplementary_style_guide/glossary_terms_conventions/general_conventions/j.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/k.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/q.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/173
=> Apply correct use of italics and quotes to j-r glossary

GUIDELINES.adoc, HISTORY.md, README.md, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc, supplementary_style_guide/introduction/about-guide.adoc, supplementary_style_guide/main.adoc, supplementary_style_guide/style_guidelines/code-commands.adoc, supplementary_style_guide/style_guidelines/formatting.adoc, supplementary_style_guide/style_guidelines/grammar.adoc, supplementary_style_guide/style_guidelines/legal.adoc, supplementary_style_guide/style_guidelines/links.adoc, supplementary_style_guide/style_guidelines/managed-services.adoc, supplementary_style_guide/style_guidelines/release-notes.adoc
Per #264
Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-ibm.html
=> Updating to use the proper name of the IBM Style guide

supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
Addresses issue #187. 
Preview: http://file.rdu.redhat.com/~ahoffer/style_guide/disconnected/master.html#disconnected
=> Adding disconnected term for OpenShift

supplementary_style_guide/main.adoc
=> Removing possessive

supplementary_style_guide/style_guidelines/formatting.adoc, supplementary_style_guide/style_guidelines/grammar.adoc
Addendum to PR 265:
https://github.com/redhat-documentation/supplementary-style-guide/pull/265
=> Updates to avoid 'guide guidance'

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
Summary: This PR addresses #206 by adding guidance for usage of `Basic authentication`.
=> 206-guidance-for-basic-authentication

supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
Fixes [Issue 199](https://github.com/redhat-documentation/supplementary-style-guide/issues/199)
=> Issue 199: Removes 'through' entry from glossary

supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
Small fix to facilitate the Vale rules generation in https://github.com/redhat-documentation/vale-at-red-hat/pull/410
=> Small fix for Vale rules generation

supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
This PR updates the italic and quotation marks in the glossary (letters "G" through "I") to conform with the recommended usage from IBM Style.
Preview (RH VPN access required): 
- http://file.rdu.redhat.com/~bburt/ssg/main.html#_g
- http://file.rdu.redhat.com/~bburt/ssg/main.html#_h
- http://file.rdu.redhat.com/~bburt/ssg/main.html#_i
=> Issue 173 - update quotations and italics - G-I

supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
=> Removing part of Foreman description that is no longer applicable

supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc
See https://github.com/redhat-documentation/supplementary-style-guide/issues/289
=> Issue #289: Update glossary entry: want

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
Added back icons that were inadvertently removed in #217.
Preview: http://file.rdu.redhat.com/~ahoffer/2023/main-icons.html
=> Added missing icons

HISTORY.md, supplementary_style_guide/introduction/whats-new.adoc
Preview: http://file.rdu.redhat.com/~ahoffer/2023/main-feb23.html#february-2023
=> Updating history for February 2023

supplementary_style_guide/style_guidelines/code-commands.adoc, supplementary_style_guide/style_guidelines/formatting.adoc, supplementary_style_guide/style_guidelines/grammar.adoc, supplementary_style_guide/style_guidelines/legal.adoc, supplementary_style_guide/style_guidelines/managed-services.adoc, supplementary_style_guide/style_guidelines/release-notes.adoc, supplementary_style_guide/style_guidelines/structure.adoc, supplementary_style_guide/style_guidelines/support.adoc
=> Add {nbsp} non-breaking space to Red Hat

supplementary_style_guide/introduction/whats-new.adoc
=> updated April history

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/x.adoc
**Description:** 
This PR adds architecture guidelines to the Red Hat supplementary style guide
Still in progress, adding some more details.
=> Adding architecture guidelines to Red Hat Style guide

supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc
Found some typos while reading through the documentation for m.adoc so went ahead and corrected them for clarity.
=> Corrected typos to improve clarity

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
=> Add softirq to glossary

supplementary_style_guide/introduction/whats-new.adoc
Preview: https://file.rdu.redhat.com/~ahoffer/2023/main-may-23.html#whats-new
=> Updated history for May 2023

.github/workflows/deploy-site.yml, .gitignore
Using https://github.com/redhat-documentation/redhat-docs-template/
Preview: https://file.emea.redhat.com/aireilly/ssg_updated_design/#
=> Updates site build with new redhat-docs-template build

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
=> Adds a glossary entry for 'codebase'

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
=> Issue 312: Corrects the capitalisation of 'playbook'

supplementary_style_guide/introduction/whats-new.adoc
**Do not merge until after June 30** to make sure there are no more updates for the month of June.
Preview: https://file.rdu.redhat.com/~ahoffer/2023/main-june-23.html#june-2023
(VPN required; ignore old style)
=> [WIP] Updating history for June 2023

supplementary_style_guide/style_guidelines/formatting.adoc
Changed file: formatting.adoc
Entry: Non-breaking spaces
=> Explain why we use a non-breaking space with Red Hat.

supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc
Added an index for Elastic Load Balancing (ELB).
Fixes: [Elastic Load Balancing](https://github.com/redhat-documentation/supplementary-style-guide/issues/361)
Preview: (https://dfitzmau.github.io/previews/main.html#_e)
(VPN required; ignore old style)
=> GitHub-361: Added index for ELB

supplementary_style_guide/style_guidelines/grammar.adoc
Adds Minimalism section to the Grammar and language section of the SSG.
I used the following sources for text:
https://docs.google.com/document/d/1Er6__zrvIbnrmFTg2hizBeM3kzfdThbgi1iWCZmZXyc/edit
https://docs.google.com/document/d/1gz78zS8PyZ1rz5EmU2lQn75DKMNHVWV_KtKNAWMVb6c/edit
https://source.redhat.com/groups/public/minimalism-quality-initiative
=> added Minimalism section

supplementary_style_guide/introduction/whats-new.adoc
=> added August entry

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
Added an index item for IBM Cloud&#174; Bare Metal (Classic) as stated in Issue #373.
Fixes: https://github.com/redhat-documentation/supplementary-style-guide/issues/373
Previews: 
* [Word usage (a.adoc)](https://dfitzmau.github.io/previews/main.html#_a)
* [Word usage (o.adoc)](https://dfitzmau.github.io/previews/main.html#_o)
=> github-373-pr: Added index for AWS Region and LZ terms

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
Removes "pulldown" from the glossary
=> issue-376-remove-pulldown-entry

supplementary_style_guide/introduction/whats-new.adoc
Adding September entries.
Preview: https://file.rdu.redhat.com/~ahoffer/2023/sept-23-history.html#september-2023
**Do not merge until September is over, in case there are any late additions**
=> Updating history for September 2023

supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc
=> Issue #396 add "executable" to supplementary style guidelines

supplementary_style_guide/style_guidelines/formatting.adoc
Fixes https://github.com/redhat-documentation/supplementary-style-guide/issues/418
=> Remove "must" from wording around user-replaceable values

supplementary_style_guide/introduction/whats-new.adoc
Preview: https://file.rdu.redhat.com/~ahoffer/2023/main-november-2023.html#november-2023
=> Adding what's new for November 2023

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
Addresses Issue #424 
[Preview link](https://file.emea.redhat.com/dfitzmau/issue-424/main.html#ibm-cloud)
=> issue-424: Updated IBM name references

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
https://github.com/redhat-documentation/supplementary-style-guide/issues/366
=> Adding ingress(adj) to the SSG

.github/workflows/vale-on-pull.yml
Vale 3.0.0 introduces a breaking change to vale.ini config
=> freeze Vale version at 2.30

supplementary_style_guide/style_guidelines/formatting.adoc
Draft for addressing #224.
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-man-pages.html#man-pages
=> Adding guidance for referencing man pages

supplementary_style_guide/introduction/whats-new.adoc
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-jan-2024.html#january-2024
=> Adding what's new for January 2024

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc
Closes https://github.com/redhat-documentation/supplementary-style-guide/issues/446
=> Remove RHV terms

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc
Closes https://github.com/redhat-documentation/supplementary-style-guide/issues/447
=> Remove CloudForms terms

supplementary_style_guide/introduction/whats-new.adoc
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-feb-2024-history.html#february-2024
=> Adding what's new for February 2024

supplementary_style_guide/style_guidelines/code-commands.adoc
=> Issue #235: add some examples to root cli commands entry

.github/workflows/vale-on-pull.yml
Update Vale review action with pull request read + comment perms for reviewdog.
=> [chore] - update Vale review action

supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc, supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
Per @bredamc [feedback](https://github.com/redhat-documentation/supplementary-style-guide/pull/368#discussion_r1383325924) on the ingress definition updates I made, I'm opening a PR to add a definition for egress. 
Note to SSG team: I need to get input from other Networking writers for this, as I am not a usual writer for egress firewall, egress IP, and egress services, so hold on the reviews for merging to the SSG for now.
=> Adding egress definition

supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc, supplementary_style_guide/introduction/whats-new.adoc
Redoing branch to fix GitHub nonsense
=> March whats new backup

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
Adding "peer pods" to glossary
=> Add "peer pods" to glossary

ADMIN.adoc
=> typo fix in ADMIN.adoc

supplementary_style_guide/introduction/whats-new.adoc
Preview: https://file.rdu.redhat.com/~ahoffer/2024/april-history.html
=> Adding what's new for April 2024

supplementary_style_guide/introduction/whats-new.adoc
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main_may_2024.html#may-2024
=> Adding what's new for May 2024

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
=> Add Base64 to glossary

supplementary_style_guide/style_guidelines/support.adoc
This PR updates the tech preview template to address #491
=> issue-491-update-tech-preview-template-wording

.github/pull_request_template.md
Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/496
=> GH#496: Added PR template

supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
Incorrect indent was expanding the entire O section
Issue:
=> Fix incorrect indent in offline

supplementary_style_guide/introduction/whats-new.adoc
Issue:
N/A
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-june-24.html#june-2024
=> Adding what's new for June 2024

supplementary_style_guide/style_guidelines/links.adoc
Issue: #454 
Per style council decision, adding guidance to tell people not to use URL shorteners
=> issue-454-add-url-shortener-guidance

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
Update "content view" and "composite content view" to align with current Foreman/Satellite [contributor guidelines](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md).
Issue: None
=> Update Satellite "content view"

supplementary_style_guide/style_guidelines/structure.adoc
PR takes over from #484.
Pr for Issue #472 
[Preview link: Short descriptions](https://file.emea.redhat.com/dfitzmau/lead-in-sentence-module-472/structure.html)
=> module-lead-in-sentence-472

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
Change "Subscription Manifest" to "subscription manifest" to align with [Foreman doc guidelines](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md#capitalization)
Issue:
=> Update "Subscription Manifest"

supplementary_style_guide/introduction/about-guide.adoc, supplementary_style_guide/main.adoc
Issue:
#490
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-isg-link.html
=> GitHub-490: Adding a link to the IBM Style guide

supplementary_style_guide/introduction/whats-new.adoc
July 2024 What's New. @bergerhoffer please review.
=> added July 2024 What's New

supplementary_style_guide/style_guidelines/formatting.adoc
=> Fix missing bracket
