supplementary_style_guide/glossary_terms_conventions/product_conventions/amq7.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/azure-dotnet.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/bxms.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/ceph.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/fuse.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/jboss-eap.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/products_conventions_overview.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-cloudforms.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-openstack-platform.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-satellite6.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-virtualization.adoc

Removes:
- RH associate contacts
Adds:
- Directions for questions on product naming
- Directions for questions about product docs to contact prod docs specific emails where available.

Remove names from product specific conventions

---

supplementary_style_guide/master.adoc
supplementary_style_guide/style_guidelines/code-commands.adoc
supplementary_style_guide/style_guidelines/general-formatting.adoc

This is just commenting out placeholders for items that are on hold for further discussion, so that they do not appear in the doc when we go live.

Removing placeholders for items that are on hold

---

supplementary_style_guide/style_guidelines/links.adoc

Removing these subheadings until we decide what to do with the linking guidance PR (#28)

Commenting out links subheadings for now

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

Added line break so that the "Use it" line wasn't combined with the previous paragraph.
Also fixed she -> they in an example, to adhere with the "she" entry which recommends to avoid she/he.

Fixing line that was incorrectly combined with the previous paragraph

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc

Just saying "See _The IBM Style Guide_ for more information" made it seem like IBM SG followed the same rule (though it does provide more information about existing content vs new content to this end). Could be splitting hairs, but thought that this change might be a bit more correct / clear. :shrug:

Clarify IBM SG rec for 'host name'

---

CONTRIBUTING.md

If you don't have an SSH key set up, the clone command we have will fail. Adding SSH key as a prereq.
@mportman12 Can you review this and make sure this would have been enough info to help you? Thanks!

Adding prereq of setting up SSH key for GitHub

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc

E.g. [Wikipedia][1]:
> x86-64 (also known as x64, x86_64, AMD64 and Intel 64)[note 1] is a 64-bit version of the x86 instruction set...
and [also][2]:
> Introduced  1978 (16-bit), 1985 (32-bit), 2003 (64-bit)
Also "a ... version" and not "the ... version", because there are presumably other ways you could extend x86 to 64 bits.
[1]: https://en.wikipedia.org/wiki/X86-64
[2]: https://en.wikipedia.org/wiki/X86

AMD64: Clarify that it is 64-bit x86, and not 32-bit, etc. x86

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/j.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/k.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/x.adoc

After comparing our general glossary with the new 2020 IBM style guide, I've removed the following entries that have duplicate entries (with the same/similar guidance):
* big data
* bit rate
* front-end
* front end
* healthcare
* Internet of Things
* I/O
* ISV
* just
* kill
* license
* NFS
* NULL
* null
* on the fly
* please
* plug-in
* press
* real time
* real-time
* reboot
* runtime
* server side
* server-side
* terminate
* third party
* time zone
* type
* unmount
* usable
* X Window System
I've also fixed some entries that were not alphabetized correctly. 
*** When reviewing, note that there is NO new content. Any new content has just been moved due to proper alphabetizing.

Removing entries that are duplicated by the new IBM style guide

---

HISTORY.md
README.md

Adding a page where we list the significant updates to the guide. Current use case for it is to link to from email updates, for people to see what's new.

Adding a history page for updates

---

GUIDELINES.adoc

I moved the table around so <class> was is the same position as in the template: between <item> and <description>.
Easier to read, I think.

Reordered glossary entry table so <class> was in the right place

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc

[Revised 2021-06-23]
Following the guidance of ISG, I replaced the capitalized "Internet" with the lowercased "internet" throughout the guide.
[original PR text]
~~I'm adding a glossary entry for "Internet" because:~~
* ~~we tend to use the capitalized form in our docs~~
* ~~without this entry, writers must follow IBM, which prefers the lowercase "internet"~~
~~For the record, I prefer the lowercase form. Style guides and dictionaries are all moving in this direction, with the notable exception of Merriam Webster.~~
~~But until we're prepared to make that commitment, we need to provide clear guidance to writers.~~
~~I've also changed a few instances of "internet" to "Internet" in this guide.~~

Replaced "Internet" with "internet" according to ISG guidelines

---

supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-enterprise-linux.adoc
supplementary_style_guide/master.adoc

Per conversations with Sharon and Andrea, added RHEL to the product-specific conventions list and added migration-related terminology to the RHEL module. 
The migration terminology is also included in [RHEL upgrades documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index#ref_key-migration-terminology_upgrading-from-rhel-7-to-rhel-8). Because the Supplementary Style Guide is internal, I removed some sentences from the terminology definitions that were more customer-focused.

Add RHEL to product-specific conventions list

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc

Added icons to glossary terms C, D, and E as part of Andrea's larger effort. Note that this PR must be merged **after** [Andrea's main PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/82) or else icons won't show up correctly in the guide.

Added icons to glossary terms C, D, and E

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/j.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/k.adoc

Added term usage icons for letters F, G, H, I, J, and K in the glossary.
Please merge PR #82 before merging this one, otherwise the icons will not render properly.

added glossary term usage icons for F, G, H, I, J, and K

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/symbols.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/x.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/y.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/z.adoc

Added term usage icons for letters S, T, Symbols, U, V, W, X, Y, and Z in the glossary.
This MR continues on from https://github.com/redhat-documentation/supplementary-style-guide/pull/92

Added glossary term usage icons for S-Z

---

supplementary_style_guide/glossary_terms_conventions/product_conventions/jboss-eap.adoc

Updated jboss-eap.adoc file with additional entries based on Bob's previous pull request at https://github.com/redhat-documentation/supplementary-style-guide/pull/55.
Revised descriptions to include full sentences. Cleaned up formatting and added xrefs for links between terms. Sorted entries alphabetically.

Add EAP terms to jboss-eap.adoc based on Bob's updates

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc

Per discussion in today's style meeting, I've made the following changes for the term "Operator":
* Duplicated the "Operator" entry to the general conventions instead of just the OpenShift conventions.
* Updated the "Operator" entry with some helpful info from the [OpenShift doc guidelines](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#operator-capitalization) on the same entry.
* Expanded the entry to clarify capitalization considerations and examples, and to clarify that other types of Kubernetes components that remain lowercase when general or monospaced and proper when specific.
* Updated the same entry in the OpenShift conventions page for consistency between the two.
Entry previews:
* …

Update Operator conventions

---

supplementary_style_guide/style_guidelines/general-formatting.adoc

* I've seen some questions recently about combining the `subs` attr when also applying source highlighting, so I've added an example showing the comma-style syntax for listing multiple.
* Threw in some AKAs for "user-replaced values", since it might be helpful for people trying to CTRL+F the guide (many CCS folks refer to them still as "replaceables" and the IBM SG calls them "variable values").
~~Added `subs="attributes+"` to the list of suggestions, as it's the one used the most in the `openshift-docs` repo.~~

Add alts for "user-replaced value"

---

supplementary_style_guide/style_guidelines/general-formatting.adoc

Draft of content to provide guidance for referring to future releases, plans, or events. 
Addresses issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/51
Please comment and provide feedback.

Add guidance to avoid future predictions

---

supplementary_style_guide/style_guidelines/general-formatting.adoc

This PR adds text about deprecation notices to the guidelines for making statements about the future. See the discussion in the following issue for more information: https://github.com/redhat-documentation/supplementary-style-guide/issues/51
It also adds "yes" and "no" icons to the sample sentences to make them more consistent with other samples in the guide.

Add exception for deprecation notices to predictions guidelines

---

supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-single-sign-on.adoc
supplementary_style_guide/master.adoc

Added a new section for Red Hat Single Sign-On.
The source content was from: 
https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/overview/concepts.adoc
I made a couple very light edits for IBM style too

Added glossary for Single Sign-On

---

supplementary_style_guide/glossary_terms_conventions/product_conventions/red-hat-virtualization.adoc

Updates to RHV glossary  
- removing terms that don't exist anymore in the UI or the documentation set
- updating links to documents
- removing examples with links to illustrations that are no longer in the doc det

update_rhv_glossary preliminary updates to RHV glossary

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/j.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc

Minor style updates related to UNIX

---

supplementary_style_guide/style_guidelines/specific-doc-types.adoc

Addresses https://github.com/redhat-documentation/supplementary-style-guide/issues/144 to fix some issues with the grammar and meaning of the explanation and examples for removal and deprecation notices

Fix grammatical errors and problems with deprecation notice and removal notice

---

supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc

Added OpenShift Cluster Manager entry to product conventions to improve CCS knowledge of how to refer to it, and keep consistent across different docs sets. This includes avoiding the OCM acronym.
Please see this related Jira with guidance from product management:
https://issues.redhat.com/browse/OSSDOCS-23

Added entry for OpenShift Cluster Manager 

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc

Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/153
PR updates the CCS Style Guide as follows:
- Adds a global TLS definition
- Adds a global TLS handshake definition
- Updates the SSL definition
- Updates the SSL/TLS definition
SME reviewed content: [Google Doc](https://docs.google.com/document/d/1lMlNz-ugsizrGDR6N6XHgsVCG0Fs2XbXQqkeAhCmhGs/edit?pli=1#)

Add global entry for TLS and TLS handshake

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc

While I was browsing the glossary, I noticed that the entry for "application" included what I'm assuming was a copy/paste error. I also added double quotation marks around the term "application" where it was being referred to as a term.

updating application glossary entry

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc

Hi all, 
based on a request from a colleague from networking, I updated the term cookie so that it no longer contains the information about storing cookies in a text file. Because browsers no longer use a text file to store cookies. For example, Firefox switched from cookies.txt to an SQLite database in version 3.0 (which was released 2008).

Update the term "cookie"

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

These updates are part of the work for #195. 
I added an entry to the glossary for Red Hat OpenShift Data Foundation, cross referenced it with the entry for Red Hat OpenShift Container Storage, and updated any glossary entries that mention OCS to note that OCS is now ODF.

adding ODF entry to glossary and updating references to OCS

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

I rewrote the description because it contained incorrect information (Samba free software, not freeware). Additionally, "other commonly shared resources" made not much sense. Samba only shares printers and files. What else it does is that it provides domain services, but that's not sharing. It was time to update this glossary entry.
Andreas Schneider (Upstream and Red Hat Samba developer) ACK'ed the new description.

Rewrote "Samba" glossary entry

---

supplementary_style_guide/style_guidelines/general-formatting.adoc

In documentation people often use IP addresses from ranges reserved for private networks, such as 192.168.0.0/24. However, there are IP ranges exclusively reserved for documentation purposes to avoid conflicts and confusion. We should use them. Same for MAC addresses.
This enhancement also lists the RFCs that define the ranges.

Added "IP addresses and MAC addresses"

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/j.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc

Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/194
Added missing links for the JBoss Way entry.
Updated both the Red Hat Data Grid entry and the Red Hat JBoss Data Grid entry to clarify when the rebranding occured.

Addressed inaccuracies with Data Grid product name entries and added link for Red Hat Way for JBoss EAP entry 

---

supplementary_style_guide/style_guidelines/release-notes.adoc
supplementary_style_guide/style_guidelines/support.adoc

Updates:
* The release notes doc text for TP features to link to the new TP section instead of duplicating.
* The TP template to not use a raw URL
Previews:
* http://file.rdu.redhat.com/~ahoffer/2022/main.html#technology-preview-guidance
* http://file.rdu.redhat.com/~ahoffer/2022/main.html#release-notes-doc-texts

Linking to TP template and updating link text

---

supplementary_style_guide/introduction/about-guide.adoc
supplementary_style_guide/main-stylepedia.html

Per #236, linking to the stylepedia style guide, in case folks outside of CCS land on our SSG.
Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-stylepedia.html#_about_this_guide
@daobrien to add a similar link in the stylepedia landing page and guides to link to the SSG for CCS folks.

Adding link to stylepedia style guide

---

supplementary_style_guide/style_guidelines/formatting.adoc

Added non-breaking space subsection to the Formatting section. 
Based on [issue #196](https://github.com/redhat-documentation/supplementary-style-guide/issues/196).
@redhat-documentation/ccs-style-council please review.

added NBSP section

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc

There are three broad installation methods for OpenShift Container Platform:
- Installer-provisioned infrastructure
- User-provisioned infrastructure
- Assisted Installer
Assisted Installer is the newest method, it appears in OCP docs from 4.10. However, no corresponding term exists in the SSG for Assisted Installer. I have talked to the Assisted Installer writers and there is some use of AI, as an acronym for Assisted Installer, creeping into the [docs](https://docs.openshift.com/container-platform/4.9/installing/installing_sno/install-sno-installing-sno.html). There is obvious confusion with artificial intelligence here, and also for parallelism with the other installation methods, which forbid using IPI/UPI per the SSG glossary, we should add Assisted Installer to the glossary with …

Adding glossary term for the Assisted Installer and incorrect usage

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
supplementary_style_guide/style_guidelines/support.adoc

A description of Developer Preview scope has been added in the customer portal: https://access.redhat.com/support/offerings/devpreview 
This PR adds the term "Developer Preview" to the SSG terms list and the Support section of the SSG. Related to https://github.com/redhat-documentation/supplementary-style-guide/issues/101
Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-dev-preview.html#developer-preview-guidance

Add Developer Preview guidance to the SSG

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

Added entries for the following terms to the glossary per [Issue 241](https://github.com/redhat-documentation/supplementary-style-guide/issues/241):
- Sticky bit
- Sticky session
- Session persistence
@redhat-documentation/ccs-style-council please review

Add entries for sticky terms

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc
supplementary_style_guide/introduction/whats-new.adoc
supplementary_style_guide/style_guidelines/links.adoc
supplementary_style_guide/style_guidelines/managed-services.adoc
supplementary_style_guide/style_guidelines/release-notes.adoc

ISG appears to prefer the style "For more information, see [x]" for citations/references (e.g., https://www.ibm.com/docs/en/ibm-style?topic=references-citations). Mostly the SSG shows this form in examples, but this PR cleans up the following:
* Syncs up any similar instances to use the ISG preferred form
* Updates an old entry for "see" that did not conform and was therefore a little misleading

Clean up citation/reference examples per ISG

---

supplementary_style_guide/style_guidelines/links.adoc

This PR defines more clearly what sites are considered to be "external" and clarifies that including links to upstream documentation does not imply that RH supports the content on those sites.
It also clarifies and simplifies the wording for other external link guidelines.
Preview (RH VPN required): http://file.rdu.redhat.com/~bburt/291-define-external-sites/main.html#external-links

Issue291 - define external sites

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/style_guidelines/release-notes.adoc

This PR swaps out three "recreate" entries and replaces them with "re-create" as per Issue request #342 
Preview links (search for "re-create"):
* [Release notes doc texts](https://dfitzmau.github.io/previews/main.html#release-notes-doc-texts)
* [P](https://dfitzmau.github.io/previews/main.html#_p)

Updated recreate entries in SSG

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/numbers.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/x.adoc
supplementary_style_guide/main.adoc

* Moved 2 entries that started with numbers to a separate "0-9" section
* Also removed an incorrect form for AMD64 that was the same as the correct entry name
* Renamed "Symbols" to "Special characters" (and moved to the beginning of the glossary)
Preview: https://file.rdu.redhat.com/~ahoffer/2023/main-numbers.html#_0_9

Moving number entries to separate number section

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

Proposed fix for issue #315 (Correct spelling and capitalization for "sosreport").

Adds glossary entries for 'sos report' and 'sosreport'

---

supplementary_style_guide/style_guidelines/formatting.adoc

Add Titles and Headings section to mandate using sentence case instead of title case.
From [Issue 317](https://github.com/redhat-documentation/supplementary-style-guide/issues/317).

added Titles and headings section

---

supplementary_style_guide/style_guidelines/graphical-interfaces.adoc

To address #347
Preview: https://file.rdu.redhat.com/~ahoffer/2023/main-ui-elements.html#user-interface-elements
(must be on VPN + ignore that the style looks different)

GitHub-347: Clarifying not to bold unlabeled GUI elements

---

GUIDELINES.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

#332 removes [discrete] tags to allow the glossary entries to be a clickable link. Updating the glossary entry template to show this, and to clean up a few new instances that were introduced before the above PR merged.

Updated guidelines and cleaned up a few discrete tags

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc

Quick fix to remove a discrete tag. This is a follow-up PR for https://github.com/redhat-documentation/supplementary-style-guide/pull/363
Not sure if preview is necessary, but I created on: https://dfitzmau.github.io/previews/main.html#_e

remove-discrete-tags: Removed a dangling discrete tag

---

.github/workflows/build-pdf-release.yml
.gitignore
supplementary_style_guide/introduction/about-guide.adoc

Related to work done in https://github.com/redhat-documentation/supplementary-style-guide/pull/340, this PR adds a basic PDF output GitHub action to the SSG project.
Every merged commit triggers the PDF to be built as a release deliverable. Example: https://github.com/aireilly/adoc-test/releases/tag/v13

Add PDF release GitHub action

---

supplementary_style_guide/style_guidelines/formatting.adoc

Addresses issue 303, add guidance for replaceable variables in output. In "User-replaced values" section, added a bullet to describe the council's recommendation, and added an example. Should we also make parallel changes for the "User-replaced values for XML" section?

Update user-replaced value guidance for output

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc

This PR removes unnecessary information and incorrect forms for terms such as "agnostic", "client-side", "cloud", "colocate", "data center", and "DevOps". The changes ensure consistency and accuracy in the usage of these terms.
Addresses item 1 for #147 
Hi @bergerhoffer! :) I could not access the IBM link mentioned in the first checkbox in issue #147, so I'm not sure if other words need to be removed besides the ones you listed.

fix: Remove terms 

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc

Recent IBM Cloud updates were made to the guide: https://github.com/redhat-documentation/supplementary-style-guide/pull/359 . The request for a usable `IBM eServer System i` term is no longer valid. 
Closes number 12 in #147
[See ibm-eserver-system-i and iSeries](https://file.emea.redhat.com/dfitzmau/item-12-147/main.html#_i)

item-12-147

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

22. https://redhat-documentation.github.io/supplementary-style-guide/#_s
Shadowman (noun): In the "See also" section, maybe link directly to the page that refers to Shadowman (https://www.redhat.com/en/about/brand/standards/history) instead of to the top-level brand page (https://www.redhat.com/en/about/brand/standards)? [Volunteer needed]
I updated the link based on the description above and updated the link title to reflect this change.
Closes number 22 in #147

Update see also link in Shadowman entry to point to brand history page

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc

Responding to [issue 377](https://github.com/redhat-documentation/supplementary-style-guide/issues/377): Adding "inject" to RH SSG glossary based on its usage (and resulting questions about whether it's allowed) in the RHTAP UI.

Adding glossary entry for 'inject'

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc

No direct word usage entry exists in the IBM SG for "PC", but I did find usage info in the "microcomputer" word usage entry. 
Closes number 17 in #147
https://file.emea.redhat.com/dfitzmau/item-17-147/main.html#_p -- See the PC entry

item-17-147

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc

PR for [issue 385](https://github.com/redhat-documentation/supplementary-style-guide/issues/385)
Add "Ansible Rulebook" to the glossary

github-385-pr: Add Ansible Rulebook to glossary

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

This PR turns the "because" entry into "since" and places the revised entry into the S file 
Closes number 10 in #147

feat: adding since to S file

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

I updated the spec file entry based on the following sources:
* https://linux.die.net/man/8/rpmbuild
* https://access.redhat.com/documentation/fr-fr/red_hat_enterprise_linux/9/html/packaging_and_distributing_software/assembly_what-a-spec-file-is_packaging-software
I noticed that the Fedora docs use the term "RPM spec file", but the RPM owns the spec file so I made such references into possessive constrcuts. 
Closes number 23 in #147
https://file.emea.redhat.com/dfitzmau/item-23-147/main.html#_s

item-23-147

---

supplementary_style_guide/style_guidelines/code-commands.adoc

Expanded the IP addresses section to point out that the guidance on ranges to use actually comes from the RFCs.
Fixes: #334
Preview: https://file.rdu.redhat.com/~ahoffer/2023/main-ip-address.html#ip-addresses-and-mac-addresses
(VPN required; ignore old style)

GitHub-334: Adding details and RFCs for IP address ranges

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc

Updates to "header bar" entry in Glossay for RHV - the new UI was created last year, 
I am the writer who updated the RHV VM Portal guide.
reference - new entry in the Introduction to the VM Portal - 
https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/introduction_to_the_vm_portal/index#Graphical_User_Interface_elements

updating glossary items for RHV VM Portal "header bar"

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc

Added glossary entries for hashbang, interpreter directive, and shebang.
Duplicates work in [PR#416](https://github.com/redhat-documentation/supplementary-style-guide/pull/416). #416 was old enough that updating that PR would create merge conflicts, so I am creating this PR and closing 416.
@bergerhoffer @ndeevy @bredamc please review.

added glossary entries

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc

Purpose: This PR standardizes the capitalization and short form of Red Hat Customer Portal.
Fixes https://github.com/redhat-documentation/supplementary-style-guide/issues/384
Request for Review:
@IngridT1, @mportman12, @bergerhoffer, @ndeevy, @bredamc - your insights and feedback on these changes would be greatly appreciated. Thank you.

Standardize the capitalization and short form of Red Hat Customer Portal

---

supplementary_style_guide/style_guidelines/graphical-interfaces.adoc

The current Patternfly links in the SSG are out of date and hit 404 errors. This PR updates the links to the correct URLs.

updated Patternfly links

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc

Just a few tweaks I noticed. The incorrect forms should be single words/phrases, not sentences

A few minor tweaks to recent updates

---

supplementary_style_guide/style_guidelines/formatting.adoc

Update draft for https://github.com/redhat-documentation/supplementary-style-guide/issues/390

Issue#390 - bold commands in codeblocks

---

supplementary_style_guide/style_guidelines/legal.adoc
supplementary_style_guide/style_guidelines/release-notes.adoc

This PR adds a sentence that explicitly states that deprecation notices are allowed to mention specific release timelines according to which functionality will be deprecated and removed.

issue-420: clarify-deprecation-notice-wording

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/j.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/k.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/q.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/x.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/z.adoc

To make future sweeps of updating "Red Hat" to "Red{nbsp}Hat", I'm removing the comments above some entries that were from the restructuring in 2022. These comments are no longer needed.

Removing outdated comments from restructuring

---

.github/workflows/vale-on-pull.yml

Adding continue-on-error: true to Vale action. Vale/reviewdog should never cause the PR to fail.

Adding continue-on-error: true to Vale action

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/a.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/f.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/g.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/h.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/m.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/t.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/u.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/v.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc

Taking over #335 to get it over the finish line.
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-storage-terms.html#_word_usage

Adding storage gloss terms

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/q.adoc

There was a minor correction required in the QETH.adoc file about incorrect markup.

Fixed a Minor correction in ASCIIDOC Markup

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc
supplementary_style_guide/glossary_terms_conventions/general_conventions/o.adoc

Addresses https://github.com/redhat-documentation/supplementary-style-guide/issues/471
The entry for _disconnected_ is not addressed with this PR per the guidance in https://github.com/redhat-documentation/supplementary-style-guide/blob/main/GUIDELINES.adoc#contributing-a-style-guideline-entry.

SSG#471: adds offline glossary entry

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/n.adoc

Nmstate is part of RHEL and used by RHEL applications and layered products, such as OpenShift.
https://nmstate.io/

Add Nmstate to glossary

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc

Remove "Red Hat Network Proxy Server" and "Red Hat Network Satellite Server" because these terms are obsolete. They have been replaced by Capsule Server and Satellite Server.
Issue:

Remove Satellite network servers

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/p.adoc

Satellite no longer capitalizes "Product".
Issue: https://github.com/theforeman/foreman-documentation/issues/3148

Remove Satellite "Product"

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/i.adoc

…established usage
Issue 483, change identity provider acronym from IDP to IdP to match …
Issue:
https://github.com/redhat-documentation/supplementary-style-guide/issues/483

Issue 483, change identity provider acronym from IDP to IdP to match established usage

---

supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc

Add "backup storage location"

---

supplementary_style_guide/style_guidelines/code-commands.adoc

Issue: None
Additional information: Review comments in https://github.com/redhat-documentation/supplementary-style-guide/pull/517

Ellipses yaml code blocks

---

supplementary_style_guide/style_guidelines/release-notes.adoc

Issue:
The current guidance for writing release notes was insufficient; we propose expanding this section with general guidance that should address commonly encountered problems in RN texts.
Draft prepared by [Ingrid Towey](mailto:itowey@redhat.com), [Darragh Fitzmaurice](mailto:dfitzmau@redhat.com), [James Smith](mailto:jamsmith@redhat.com), [Brian Angelica](mailto:bangelic@redhat.com), [Jan Fiala](mailto:jafiala@redhat.com)

Add general style guidance based on the Release Note Improvement Initiative, Working Group 1

---

supplementary_style_guide/style_guidelines/formatting.adoc

This PR addresses issue #532 and adds a line on separating a command and its related example output into individual code blocks and update examples.

single_cmd_per_codeblock

---

supplementary_style_guide/style_guidelines/release-notes.adoc

Issue:
The previous guidance for release note categories was incomplete, insufficient, and at times incorrect.
This proposal is the result of Working Group 1 of the Release Notes Improvement Initiative.
For discussions, message [#project-wg1-release-notes-improvement-style](https://redhat.enterprise.slack.com/archives/C0964CRJW3V)

Add style guidance for release note types

---

supplementary_style_guide/style_guidelines/code-commands.adoc
supplementary_style_guide/style_guidelines/formatting.adoc

Guidance for explaining a command or elements in a code block
Issue:
https://github.com/redhat-documentation/supplementary-style-guide/issues/540 
Additional information: 
**TLDR:** Stop using callouts in code blocks, use simple sentences, bulleted/unordered lists, Distribution lists or Note style as appropriate. This needs to be done before we migrate to the new tool.
**Problem statement:** 
- **Callouts are not supported in DITA**: Unlike AsciiDoc, DITA does not support callouts as a method to add annotations to specific lines in verbatim blocks.  
- **Callouts do not work for AI**: Because callouts are not supported in DITA, (and we're not making changes to DITA-OT) there isn't semantic markup for an AI agent to understand what is happening or to output that semantic markup properly.
- …

Add guidance on explaining commands and variables
